/*
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import javax.swing.JOptionPane;
import logica.Destino;

/**
 *
 * @author juanfe
 */
public class pnEditarVuelo extends javax.swing.JPanel {

    /**
     * Creates new form pnPrincipal
     */
    public pnEditarVuelo() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        lbTitulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        lbTitulo.setForeground(Color.black);
        lbInstrucciones.putClientProperty("FlatLaf.style", "font: light $h3.regular.font");
        lbInstrucciones.setForeground(Color.black);
        lbDestino.putClientProperty("FlatLaf.styleClass", "large");
        lbDestino.setForeground(Color.black);
        lbDia.putClientProperty("FlatLaf.styleClass", "large");
        lbDia.setForeground(Color.black);
        lbMes.putClientProperty("FlatLaf.styleClass", "large");
        lbMes.setForeground(Color.black);
        lbAnio.putClientProperty("FlatLaf.styleClass", "large");
        lbAnio.setForeground(Color.black);
        lbHora.putClientProperty("FlatLaf.styleClass", "large");
        lbHora.setForeground(Color.black);
        lbPrecio.putClientProperty("FlatLaf.styleClass", "large");
        lbPrecio.setForeground(Color.black);
        lbID.putClientProperty("FlatLaf.styleClass", "large");
        lbID.setForeground(Color.black);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbDestino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        lbDia = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        btEdicionVuelo = new javax.swing.JButton();
        lbAnio = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        lbHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lbPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbInstrucciones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        pnBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnBackground.setMinimumSize(new java.awt.Dimension(750, 430));
        pnBackground.setPreferredSize(new java.awt.Dimension(750, 430));

        lbTitulo.setText("Edición de un Vuelo");

        lbDestino.setText("Destino:");

        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });

        lbDia.setText("Dia:");

        btEdicionVuelo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btEdicionVuelo.setForeground(new java.awt.Color(0, 0, 0));
        btEdicionVuelo.setText("Editar");
        btEdicionVuelo.setBorder(null);
        btEdicionVuelo.setBorderPainted(false);
        btEdicionVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdicionVueloActionPerformed(evt);
            }
        });

        lbAnio.setText("Año:");

        lbMes.setText("Mes:");

        lbHora.setText("Hora:");

        lbPrecio.setText("Precio:");

        lbID.setText("ID :");

        lbInstrucciones.setText("Ingrese el ID del Vuelo a Editar y las Propiedades que desea cambiar:");

        javax.swing.GroupLayout pnBackgroundLayout = new javax.swing.GroupLayout(pnBackground);
        pnBackground.setLayout(pnBackgroundLayout);
        pnBackgroundLayout.setHorizontalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addGap(96, 96, 96))
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBackgroundLayout.createSequentialGroup()
                                .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addComponent(lbDia, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDia, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addComponent(lbMes, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMes, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                        .addGap(35, 35, 35)
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHora, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(lbAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addComponent(lbPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addComponent(lbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addGap(33, 33, 33)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(btEdicionVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addComponent(lbInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                        .addGap(59, 59, 59)))
                .addGap(176, 176, 176))
        );
        pnBackgroundLayout.setVerticalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHora, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMes, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(txtMes, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEdicionVuelo)
                .addGap(212, 212, 212))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEdicionVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdicionVueloActionPerformed
        // TODO add your handling code here:
         try {
            int id = Integer.parseInt(txtID.getText());

            if (txtDestino.getText().equals("") == false) {
                vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id).setDestino(new Destino(txtDestino.getText()));
            }

            if (txtAnio.getText().equals("") == false) {
                vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id).setAño(Integer.parseInt(txtAnio.getText()));
            }

            if (txtDia.getText().equals("") == false) {
                vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id).setDia(Integer.parseInt(txtDia.getText()));
            }
            if (txtMes.getText().equals("") == false) {
                vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id).setMes(Integer.parseInt(txtDia.getText()));
            }

            if (txtHora.getText().equals("") == false) {
                vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id).setHora(txtHora.getText());
            }

            if (txtPrecio.getText().equals("") == false) {
                vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id).setPrecio(Double.parseDouble(txtAnio.getText()));
            }

            txtAnio.setText("");
            txtDestino.setText("");
            txtDia.setText("");
            txtHora.setText("");
            txtID.setText("");
            txtMes.setText("");
            txtPrecio.setText("");

            JOptionPane.showMessageDialog(pnBackground, "Vuelo Editado");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(pnBackground, "Error al Editar");
            txtID.requestFocus();

        }
    }//GEN-LAST:event_btEdicionVueloActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdicionVuelo;
    private javax.swing.JLabel lbAnio;
    private javax.swing.JLabel lbDestino;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbInstrucciones;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
