/*
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import javax.swing.JOptionPane;
import logica.Usuario;

/**
 *
 * @author juanfe
 */
public class pnRegistro extends javax.swing.JPanel {

    private static Usuario admin;
    /**
     * Creates new form pnPrincipal
     */
    public pnRegistro() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        lbTitulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        lbTitulo.setForeground(Color.black);
        lbNombreRegistro.putClientProperty("FlatLaf.styleClass", "large");
        lbNombreRegistro.setForeground(Color.black);
        lbIdentificacionRegistro.putClientProperty("FlatLaf.styleClass", "large");
        lbIdentificacionRegistro.setForeground(Color.black);
        lbContrasenaRegistro.putClientProperty("FlatLaf.styleClass", "large");
        lbContrasenaRegistro.setForeground(Color.black);
    }
     
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbIdentificacionRegistro = new javax.swing.JLabel();
        lbNombreRegistro = new javax.swing.JLabel();
        txtNombreRegistro = new javax.swing.JTextField();
        txtIdentificacionRegistro = new javax.swing.JTextField();
        lbContrasenaRegistro = new javax.swing.JLabel();
        txtContraseñaRegistro = new javax.swing.JTextField();
        btSignUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        pnBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnBackground.setMinimumSize(new java.awt.Dimension(750, 430));
        pnBackground.setPreferredSize(new java.awt.Dimension(750, 430));

        lbTitulo.setText("Registro de Nuevo Administrador");

        lbIdentificacionRegistro.setText("Identificacion");

        lbNombreRegistro.setText("Nombre");

        lbContrasenaRegistro.setText("Contraseña:");

        btSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btSignUp.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btSignUp.setForeground(new java.awt.Color(0, 0, 0));
        btSignUp.setText("Registrar");
        btSignUp.setBorder(null);
        btSignUp.setBorderPainted(false);
        btSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBackgroundLayout = new javax.swing.GroupLayout(pnBackground);
        pnBackground.setLayout(pnBackgroundLayout);
        pnBackgroundLayout.setHorizontalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(lbIdentificacionRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(txtIdentificacionRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                                .addGap(220, 220, 220)))
                        .addGap(96, 96, 96))
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addComponent(lbContrasenaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addGap(316, 316, 316))
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addComponent(btSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addGap(316, 316, 316))))
        );
        pnBackgroundLayout.setVerticalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificacionRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtIdentificacionRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContrasenaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSignUp)
                .addGap(246, 246, 246))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUpActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreRegistro.getText();
        Long documento = Long.valueOf(txtIdentificacionRegistro.getText()); //Implementar try catch de error en parselong
        String contraseña = txtContraseñaRegistro.getText();
        admin = new Usuario(nombre, documento, contraseña);
        JOptionPane.showMessageDialog(pnBackground, "Usuario Creado Exitosamente");
        
        txtContraseñaRegistro.setText("");
        txtIdentificacionRegistro.setText("");
        txtNombreRegistro.setText("");
    }//GEN-LAST:event_btSignUpActionPerformed

    public static Usuario getAdmin() {
        return admin;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSignUp;
    private javax.swing.JLabel lbContrasenaRegistro;
    private javax.swing.JLabel lbIdentificacionRegistro;
    private javax.swing.JLabel lbNombreRegistro;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JTextField txtContraseñaRegistro;
    private javax.swing.JTextField txtIdentificacionRegistro;
    private javax.swing.JTextField txtNombreRegistro;
    // End of variables declaration//GEN-END:variables
}
