/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import logica.Aeropuerto;
import logica.Vuelo;

/**
 *
 * @author juanfe
 */
public class pnReporteVuelos extends javax.swing.JPanel {

    /**
     * Creates new form pnPrincipal
     */
    public pnReporteVuelos() {
        initComponents();
        InitStyles();
    }
    
    private void InitStyles() {
        lbTitulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        lbTitulo.setForeground(Color.black);
        lbInstruccionesVueloEspecial.putClientProperty("FlatLaf.style", "font: light $medium.font");
        lbInstruccionesVueloEspecial.setForeground(Color.black);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        spnListaVuelos = new javax.swing.JScrollPane();
        lstVuelos = new javax.swing.JList<>();
        lbInstruccionesVueloEspecial = new javax.swing.JLabel();
        btReporteEspecial = new javax.swing.JButton();
        txtIDVueloEspecial = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));

        pnBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnBackground.setMinimumSize(new java.awt.Dimension(750, 430));
        pnBackground.setPreferredSize(new java.awt.Dimension(750, 430));

        lbTitulo.setText("Reporte de Vuelos");

        lstVuelos.setBackground(new java.awt.Color(255, 255, 255));
        lstVuelos.setForeground(new java.awt.Color(0, 0, 0));
        spnListaVuelos.setViewportView(lstVuelos);

        lbInstruccionesVueloEspecial.setText("Para ver el Reporte de un Vuelo en especifico ingrese su ID:");

        btReporteEspecial.setBackground(new java.awt.Color(255, 255, 255));
        btReporteEspecial.setForeground(new java.awt.Color(0, 0, 0));
        btReporteEspecial.setText("Reporte Vuelo");
        btReporteEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteEspecialActionPerformed(evt);
            }
        });

        txtIDVueloEspecial.setBackground(new java.awt.Color(255, 255, 255));
        txtIDVueloEspecial.setForeground(new java.awt.Color(0, 0, 0));
        txtIDVueloEspecial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIDVueloEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDVueloEspecialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBackgroundLayout = new javax.swing.GroupLayout(pnBackground);
        pnBackground.setLayout(pnBackgroundLayout);
        pnBackgroundLayout.setHorizontalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
                            .addComponent(spnListaVuelos))
                        .addGap(24, 24, 24))
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addComponent(lbInstruccionesVueloEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDVueloEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btReporteEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142))))
        );
        pnBackgroundLayout.setVerticalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInstruccionesVueloEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btReporteEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDVueloEspecial))
                .addGap(18, 18, 18)
                .addComponent(spnListaVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDVueloEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDVueloEspecialActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txtIDVueloEspecialActionPerformed

    private void btReporteEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteEspecialActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel model = vtSistemaAeoropuerto.getDefaultListModel();
        model.removeAllElements();
        String str = txtIDVueloEspecial.getText();
        int id = Integer.parseInt(str);
        Vuelo v = vtSistemaAeoropuerto.getAeropuertoUIS().seleccionarVuelo(id);
        model.addElement(v.ConsultarVueloEspecial());
        lstVuelos.setModel(model);
        
    }//GEN-LAST:event_btReporteEspecialActionPerformed

    public JButton getBtReporteEspecial() {
        return btReporteEspecial;
    }

    public void setBtReporteEspecial(JButton btReporteEspecial) {
        this.btReporteEspecial = btReporteEspecial;
    }

    public JList<String> getLstVuelos() {
        return lstVuelos;
    }

    public void setLstVuelos(JList<String> lstVuelos) {
        this.lstVuelos = lstVuelos;
    }

    public JPanel getPnBackground() {
        return pnBackground;
    }

    public void setPnBackground(JPanel pnBackground) {
        this.pnBackground = pnBackground;
    }

    public JScrollPane getSpnListaVuelos() {
        return spnListaVuelos;
    }

    public void setSpnListaVuelos(JScrollPane spnListaVuelos) {
        this.spnListaVuelos = spnListaVuelos;
    }



    public JTextField getTxtIDVueloEspecial() {
        return txtIDVueloEspecial;
    }

    public void setTxtIDVueloEspecial(JTextField txtIDVueloEspecial) {
        this.txtIDVueloEspecial = txtIDVueloEspecial;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReporteEspecial;
    private javax.swing.JLabel lbInstruccionesVueloEspecial;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JList<String> lstVuelos;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JScrollPane spnListaVuelos;
    private javax.swing.JTextField txtIDVueloEspecial;
    // End of variables declaration//GEN-END:variables
}
