/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author juanfe
 */
public class pnReportePasajeros extends javax.swing.JPanel {

    /**
     * Creates new form pnPrincipal
     */
    public pnReportePasajeros() {
        initComponents();
        InitStyles();
        initGraph();

    }

    private void InitStyles() {

    }

    private void initGraph() {
        DefaultCategoryDataset dataEdades = new DefaultCategoryDataset();
        dataEdades.setValue(vtSistemaAeoropuerto.getAeropuertoUIS().pasajerosPorEdad()[0], "Mayores de Edad", "");
        dataEdades.setValue(vtSistemaAeoropuerto.getAeropuertoUIS().pasajerosPorEdad()[1], "Menores de Edad", "");
        
        DefaultCategoryDataset dataNacionalidades = new DefaultCategoryDataset();
        dataNacionalidades.setValue(vtSistemaAeoropuerto.getAeropuertoUIS().pasajerosPorNacionalidad()[0], "Colombianos",""); 
        dataNacionalidades.setValue(vtSistemaAeoropuerto.getAeropuertoUIS().pasajerosPorNacionalidad()[1], "Extranjeros","");
        

        JFreeChart graficoBarrasEdades = ChartFactory.createBarChart("Estadisticas de Edad", "Pasajeros", "Numero de Pasajersos", dataEdades);
        
        JFreeChart graficoBarrasNacionalidades = ChartFactory.createBarChart("Estadisticas de Nacionalidad", "Pasajeros", "Numero de Pasajersos", dataNacionalidades);

        CategoryPlot plotGraficoEdades = (CategoryPlot) graficoBarrasEdades.getPlot();
        plotGraficoEdades.setBackgroundPaint(Color.WHITE);

        BarRenderer renderer = (BarRenderer) plotGraficoEdades.getRenderer();
        renderer.setBarPainter(new StandardBarPainter());

        CategoryPlot plotGraficoNacionalidad = (CategoryPlot) graficoBarrasNacionalidades.getPlot();
        plotGraficoNacionalidad.setBackgroundPaint(Color.WHITE);

        BarRenderer rendererGraficoNacionalidad = (BarRenderer) plotGraficoNacionalidad.getRenderer();
        rendererGraficoNacionalidad.setBarPainter(new StandardBarPainter());

        ChartPanel pnGraficoBarrasEdades = new ChartPanel(graficoBarrasEdades);
        pnGraficoBarrasEdades.setPreferredSize(new Dimension(320, 400));
        pnGraficoBarrasEdades.setMouseZoomable(false);
        pnGraficoBarrasEdades.setMouseWheelEnabled(false);
        pnBackground.add(pnGraficoBarrasEdades);

        ChartPanel pnGraficoBarrasNacionalidades = new ChartPanel(graficoBarrasNacionalidades);
        pnGraficoBarrasNacionalidades.setPreferredSize(new Dimension(320, 400));
        pnGraficoBarrasNacionalidades.setMouseZoomable(false);
        pnGraficoBarrasNacionalidades.setMouseWheelEnabled(false);
        pnBackground.add(pnGraficoBarrasNacionalidades);

        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barRenderer1 = new org.jfree.chart.renderer.category.BarRenderer();
        pnBackground = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 380));

        pnBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnBackground.setMaximumSize(new java.awt.Dimension(500, 300));
        pnBackground.setMinimumSize(new java.awt.Dimension(400, 300));
        pnBackground.setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jfree.chart.renderer.category.BarRenderer barRenderer1;
    private javax.swing.JPanel pnBackground;
    // End of variables declaration//GEN-END:variables
}
