/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import logica.*;
import persistencia.*;

/**
 *
 * @author juanfe
 */
public class vtSistemaAeoropuerto extends javax.swing.JFrame {

    private static Aeropuerto aeropuertoUIS = new Aeropuerto("Aeropuerto UIS");
    private static DefaultListModel defaultListModel;
    private main main;
    private static ArrayList<String> vuelosAeropuerto;

    public static DefaultListModel getDefaultListModel() {
        return defaultListModel;
    }

    public static ArrayList<String> getVuelosAeropuerto() {
        return vuelosAeropuerto;
    }

    public static void setVuelosAeropuerto(ArrayList<String> vuelosAeropuerto) {
        vtSistemaAeoropuerto.vuelosAeropuerto = vuelosAeropuerto;
    }

    /**
     * Creates new form vtSistemaAeoropuerto
     */
    public vtSistemaAeoropuerto() {
        initComponents();
        initStyles();
        setDate();
        initContent(new pnPrincipal());
        vuelosAeropuerto = aeropuertoUIS.consultarVuelosAeropuertos();
        defaultListModel = new DefaultListModel();

    }

    private void setDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        lbDate.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    private void initStyles() {

        lbNavtext.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        lbNavtext.setForeground(Color.WHITE);
        lbDate.putClientProperty("FlatLaf.style", "font: 24 $light.font");
        lbDate.setForeground(Color.WHITE);
        lbNombrePrograma.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        lbNombrePrograma.setForeground(Color.WHITE);
        lbTitulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        lbTitulo.setForeground(Color.black);

    }

    private void initContent(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0, 0);

        pnContent.removeAll();
        pnContent.add(p, BorderLayout.CENTER);
        pnContent.revalidate();
        pnContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        pnSidebar = new javax.swing.JPanel();
        lbNombrePrograma = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btLogin = new javax.swing.JButton();
        btReportesAerolineas = new javax.swing.JButton();
        btSignUp = new javax.swing.JButton();
        btEditarVuelos = new javax.swing.JButton();
        btPrincipal = new javax.swing.JButton();
        btRegistrarVuelo = new javax.swing.JButton();
        btCancelarVuelo = new javax.swing.JButton();
        btReportesVuelos = new javax.swing.JButton();
        btReportePasajeros = new javax.swing.JButton();
        pnHeader = new javax.swing.JPanel();
        lbNavtext = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();
        pnBackground = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbContrasena = new javax.swing.JLabel();
        lbIdentificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btLogin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 640));
        setSize(new java.awt.Dimension(1030, 640));

        pnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnPrincipal.setPreferredSize(new java.awt.Dimension(1020, 540));

        pnSidebar.setBackground(new java.awt.Color(13, 71, 161));
        pnSidebar.setPreferredSize(new java.awt.Dimension(270, 540));

        lbNombrePrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombrePrograma.setText("Aeropuerto");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        btLogin.setBackground(new java.awt.Color(21, 101, 192));
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.setToolTipText("");
        btLogin.setBorder(null);
        btLogin.setBorderPainted(false);
        btLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin.setPreferredSize(new java.awt.Dimension(130, 17));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btReportesAerolineas.setBackground(new java.awt.Color(21, 101, 192));
        btReportesAerolineas.setForeground(new java.awt.Color(255, 255, 255));
        btReportesAerolineas.setText("Reporte de Aerolineas");
        btReportesAerolineas.setToolTipText("");
        btReportesAerolineas.setBorder(null);
        btReportesAerolineas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReportesAerolineas.setDoubleBuffered(true);
        btReportesAerolineas.setEnabled(false);
        btReportesAerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportesAerolineasActionPerformed(evt);
            }
        });

        btSignUp.setBackground(new java.awt.Color(21, 101, 192));
        btSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btSignUp.setText("Sign Up");
        btSignUp.setToolTipText("");
        btSignUp.setBorder(null);
        btSignUp.setBorderPainted(false);
        btSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSignUp.setPreferredSize(new java.awt.Dimension(130, 17));
        btSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUpActionPerformed(evt);
            }
        });

        btEditarVuelos.setBackground(new java.awt.Color(21, 101, 192));
        btEditarVuelos.setForeground(new java.awt.Color(255, 255, 255));
        btEditarVuelos.setText("Editar Vuelo");
        btEditarVuelos.setToolTipText("");
        btEditarVuelos.setBorder(null);
        btEditarVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEditarVuelos.setDoubleBuffered(true);
        btEditarVuelos.setEnabled(false);
        btEditarVuelos.setPreferredSize(new java.awt.Dimension(130, 17));
        btEditarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarVuelosActionPerformed(evt);
            }
        });

        btPrincipal.setBackground(new java.awt.Color(21, 101, 192));
        btPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btPrincipal.setText("Principal");
        btPrincipal.setToolTipText("");
        btPrincipal.setBorder(null);
        btPrincipal.setBorderPainted(false);
        btPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPrincipal.setPreferredSize(new java.awt.Dimension(130, 17));
        btPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrincipalActionPerformed(evt);
            }
        });

        btRegistrarVuelo.setBackground(new java.awt.Color(21, 101, 192));
        btRegistrarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btRegistrarVuelo.setText("Registrar Vuelo");
        btRegistrarVuelo.setToolTipText("");
        btRegistrarVuelo.setBorder(null);
        btRegistrarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistrarVuelo.setDoubleBuffered(true);
        btRegistrarVuelo.setEnabled(false);
        btRegistrarVuelo.setPreferredSize(new java.awt.Dimension(130, 17));
        btRegistrarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVueloActionPerformed(evt);
            }
        });

        btCancelarVuelo.setBackground(new java.awt.Color(21, 101, 192));
        btCancelarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btCancelarVuelo.setText("Cancelar Vuelo");
        btCancelarVuelo.setToolTipText("");
        btCancelarVuelo.setBorder(null);
        btCancelarVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelarVuelo.setDoubleBuffered(true);
        btCancelarVuelo.setEnabled(false);
        btCancelarVuelo.setPreferredSize(new java.awt.Dimension(130, 17));
        btCancelarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarVueloActionPerformed(evt);
            }
        });

        btReportesVuelos.setBackground(new java.awt.Color(21, 101, 192));
        btReportesVuelos.setForeground(new java.awt.Color(255, 255, 255));
        btReportesVuelos.setText("Reporte de Vuelos");
        btReportesVuelos.setToolTipText("");
        btReportesVuelos.setBorder(null);
        btReportesVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReportesVuelos.setEnabled(false);
        btReportesVuelos.setPreferredSize(new java.awt.Dimension(130, 17));
        btReportesVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportesVuelosActionPerformed(evt);
            }
        });

        btReportePasajeros.setBackground(new java.awt.Color(21, 101, 192));
        btReportePasajeros.setForeground(new java.awt.Color(255, 255, 255));
        btReportePasajeros.setText("Reporte de Pasajeros");
        btReportePasajeros.setToolTipText("");
        btReportePasajeros.setBorder(null);
        btReportePasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReportePasajeros.setDoubleBuffered(true);
        btReportePasajeros.setEnabled(false);
        btReportePasajeros.setMaximumSize(new java.awt.Dimension(130, 17));
        btReportePasajeros.setMinimumSize(new java.awt.Dimension(130, 17));
        btReportePasajeros.setPreferredSize(new java.awt.Dimension(130, 17));
        btReportePasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportePasajerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSidebarLayout = new javax.swing.GroupLayout(pnSidebar);
        pnSidebar.setLayout(pnSidebarLayout);
        pnSidebarLayout.setHorizontalGroup(
            pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSidebarLayout.createSequentialGroup()
                .addGroup(pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSidebarLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRegistrarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReportesVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReportePasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReportesAerolineas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        pnSidebarLayout.setVerticalGroup(
            pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSidebarLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lbNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btRegistrarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btCancelarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btEditarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btReportesVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btReportePasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btReportesAerolineas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnHeader.setBackground(new java.awt.Color(25, 118, 210));
        pnHeader.setPreferredSize(new java.awt.Dimension(750, 150));

        lbNavtext.setText("Administración/Aeropuerto");

        lbDate.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNavtext, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbNavtext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setMinimumSize(new java.awt.Dimension(750, 430));
        pnContent.setPreferredSize(new java.awt.Dimension(0, 0));
        pnContent.setLayout(new java.awt.BorderLayout());

        pnBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnBackground.setMinimumSize(new java.awt.Dimension(750, 430));

        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("Inicio de Sesión Administrador");

        lbContrasena.setForeground(new java.awt.Color(0, 0, 0));
        lbContrasena.setText("Contraseña:");

        lbIdentificacion.setForeground(new java.awt.Color(0, 0, 0));
        lbIdentificacion.setText("Identificación:");

        btLogin1.setBackground(new java.awt.Color(255, 255, 255));
        btLogin1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btLogin1.setForeground(new java.awt.Color(0, 0, 0));
        btLogin1.setText("Iniciar Sesión");
        btLogin1.setBorder(null);
        btLogin1.setBorderPainted(false);
        btLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBackgroundLayout = new javax.swing.GroupLayout(pnBackground);
        pnBackground.setLayout(pnBackgroundLayout);
        pnBackgroundLayout.setHorizontalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnBackgroundLayout.createSequentialGroup()
                        .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnBackgroundLayout.createSequentialGroup()
                                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(txtContrasena))))
                        .addGap(218, 218, 218)))
                .addGap(96, 96, 96))
        );
        pnBackgroundLayout.setVerticalGroup(
            pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBackgroundLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdentificacion)
                    .addComponent(lbIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContrasena)
                    .addComponent(lbContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        pnContent.add(pnBackground, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addComponent(pnSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pnContent.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        pnContent.removeAll();
        pnContent.add(pnBackground);
        pnContent.repaint();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btReportesAerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportesAerolineasActionPerformed
        // TODO add your handling code here:
        initContent(new pnReporteAerolineas());
    }//GEN-LAST:event_btReportesAerolineasActionPerformed

    private void btSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUpActionPerformed
        // TODO add your handling code here:
        initContent(new pnRegistro());

    }//GEN-LAST:event_btSignUpActionPerformed

    private void btEditarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarVuelosActionPerformed
        // TODO add your handling code here:
        initContent(new pnEditarVuelo());

    }//GEN-LAST:event_btEditarVuelosActionPerformed

    private void btPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrincipalActionPerformed
        // TODO add your handling code here:
        initContent(new pnPrincipal());
    }//GEN-LAST:event_btPrincipalActionPerformed

    private void btRegistrarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVueloActionPerformed
        // TODO add your handling code here:
        initContent(new pnRegistrarVuelo());
    }//GEN-LAST:event_btRegistrarVueloActionPerformed

    private void btCancelarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarVueloActionPerformed
        // TODO add your handling code here:
        initContent(new pnCancelarVuelo());
    }//GEN-LAST:event_btCancelarVueloActionPerformed

    private void btReportesVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportesVuelosActionPerformed
        // TODO add your handling code here:
        /*
        pnReporteVuelos pnReporteVuelo = new pnReporteVuelos();
        initContent(pnReporteVuelo);
        
        defaultListModel.removeAllElements();
        for (String str : vuelosAeropuerto) {
            defaultListModel.addElement(str);
        }
        pnReporteVuelo.getLstVuelos().setModel(defaultListModel);
         */

        pnReporteVuelos pnReporteVuelo = new pnReporteVuelos();
        initContent(pnReporteVuelo);
        defaultListModel = new DefaultListModel();
        JList lstVuelo = pnReporteVuelo.getLstVuelos();
        defaultListModel.removeAllElements();
        ArrayList<String> vuelosAeropuerto = aeropuertoUIS.consultarVuelosAeropuertos();
        for (String str : vuelosAeropuerto) {
            defaultListModel.addElement(str);
            defaultListModel.addElement("  ");

        }
        lstVuelo.setModel(defaultListModel);
    }//GEN-LAST:event_btReportesVuelosActionPerformed

    private void btReportePasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportePasajerosActionPerformed
        // TODO add your handling code here:
        initContent(new pnReportePasajeros());
    }//GEN-LAST:event_btReportePasajerosActionPerformed

    private void btLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin1ActionPerformed
        // TODO add your handling code here:
        Usuario admin = pnRegistro.getAdmin();
        String pwd = new String(txtContrasena.getPassword());
        String contraseña = pwd;
        Long identificacion = Long.valueOf(txtIdentificacion.getText());
        boolean login = admin.iniciarSesion(identificacion, contraseña);
        if (login) {
            btCancelarVuelo.setEnabled(true);
            btEditarVuelos.setEnabled(true);
            btRegistrarVuelo.setEnabled(true);
            btReportePasajeros.setEnabled(true);
            btReportesVuelos.setEnabled(true);
            btReportesAerolineas.setEnabled(true);
            btLogin.setEnabled(false);
            btSignUp.setEnabled(false);
            main = new main();
            main.iniciar();
            JOptionPane.showMessageDialog(pnContent, "Login Exitoso");
        } else {
            JOptionPane.showMessageDialog(pnContent, "Login Fallido");
        }
    }//GEN-LAST:event_btLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMaterialLighterIJTheme.setup();
        UIManager.put("Button.disabledBackground", new Color(13, 71, 161));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtSistemaAeoropuerto().setVisible(true);
            }
        });
    }

    public static Aeropuerto getAeropuertoUIS() {
        return aeropuertoUIS;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarVuelo;
    private javax.swing.JButton btEditarVuelos;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btLogin1;
    private javax.swing.JButton btPrincipal;
    private javax.swing.JButton btRegistrarVuelo;
    private javax.swing.JButton btReportePasajeros;
    private javax.swing.JButton btReportesAerolineas;
    private javax.swing.JButton btReportesVuelos;
    private javax.swing.JButton btSignUp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbNavtext;
    private javax.swing.JLabel lbNombrePrograma;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnBackground;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnSidebar;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables
}
